# Project-wide Gradle settings.
# IDE (e.g. Android Studio) users:
# Gradle settings configured through the IDE are ignored when building from the command line, so be sure to have
# the following in your project's local properties to override the Gradle settings.
#locations.properties
# For more details on how to work with Gradle, please refer to the documentation at
# https://docs.gradle.org/current/userguide/build_environment.html
# Enables namespacing of each library's R class so that its R class includes only the
# resources declared in the library itself and does not include a R class from its dependencies.
android.useNewApkStructure=true
android.enableJetifier=true
org.gradle.jvmargs=-Xmx4096m
